### ISSUE TITLE
Can't login to Todoist

### ISSUE THREAD

**Issue by Yerlix** [anopensourceguy/TodoistN1#1]
After adding my client id and client secret, I tried to login into Todoist:
![image](https://cloud.githubusercontent.com/assets/3891388/12506009/fa67d070-c0eb-11e5-942d-7f2ac5603ca9.png)

But when clicking that button, I get this error:
```javascript
{"error":"redirect_uri_not_configured"}
```

**Comment by anopensourceguy** [comment]
Hey. I added in the Readme. You have to copy and add your todoist callback
url to the file mentioned in read me

**Comment by Yerlix** [comment]
Can you push your changes then? The last change on the Readme is 6 hours ago.

Btw is it the `redirect_uri` that's needs to change?

**Comment by anopensourceguy** [comment]
I added the info , i am still thinking about adding my client id and secret . :(
