### ISSUE TITLE
The client_id passed to the popup is blank

### ISSUE THREAD

**Issue by mturner** [anopensourceguy/TodoistN1#4]
When attempting to login this fails because the client_id passed in the popup is blank.  I assume this should be pre-populated as the todoist auth screen replies with: 

{"error":"invalid_client"}

I'm happy to contribute here, but wanted some feedback on where this data should be coming from.

**Comment by anopensourceguy** [comment]
Have you followed the steps of creating an app on todoist developer website
and getting credentials like client id, client secret and oauth redirect
url and add it to the file mentioned in the Readme... Thereby this plugin
will work

**Comment by jcasabona** [comment]
This doesn't seem to be mentioned in the README: 

![screenshot 2016-02-29 11 53 51](https://cloud.githubusercontent.com/assets/344910/13401696/2ce4d8a6-dedb-11e5-9808-935c0f80b589.png)

**Comment by jcasabona** [comment]
In case you need more instructions beyond that, you would go here and create a new App to get a client ID and secret. https://developer.todoist.com/appconsole.html
