### ISSUE TITLE
Fonts incorrect

### ISSUE THREAD

**Issue by visualintent** [anopensourceguy/TodoistN1#6]
Have got default system font for the Add To Todoist and Logout from Todoist in sidebar.

This is with the latest build of Nylas - 0.4.10

**Comment by mattspaeth** [comment]
I had this issue too. Checked the stylesheet and saw that 'Roboto' was specified. If user don't have this installed on their system, default system font will be used. Needs an @import statement to bring in this font.

**Comment by anopensourceguy** [comment]
merged PR which adds Nylas Pro . Thanks for reporting this issue :+1:
